package org.tsdes.spring.rest.newsrest.dto

import io.swagger.annotations.ApiModelProperty
import java.time.ZonedDateTime
import org.tsdes.spring.examples.news.constraint.Country

/**
 * Created by arcuri82 on 12-Jul-17.
 */
data class NewsDto(

        /*
            Internally, the id is going to be a long value.
            But maybe in the future we could change it.
            So, an option is to just use a string, because
            anyway those ids are generated by the server, and
            not the client
         */
        @ApiModelProperty("The id of the news")
        var id: String? = null,

        @ApiModelProperty("The id of the author that wrote/created this news")
        var authorId: String? = null,

        @ApiModelProperty("The text of the news")
        var text: String? = null,

        @ApiModelProperty("The country this news is related to")
        @Country
        var country: String? = null,


        @ApiModelProperty("When the news was first created/published")
        var creationTime: ZonedDateTime? = null
)