package org.tsdes.spring.rest.newsrest.dto

import io.swagger.annotations.ApiModelProperty
import java.time.ZonedDateTime
import org.tsdes.spring.examples.news.constraint.Country

/**
 *  A data transfer object (DTO) is what we will use to represent and (un)marshal
 *  JSon objects.
 *
 *  This is just a POJO (plain old Java object), with no logic, just data.
 *  Also note how Swagger is used here to provide documentation.
 *
 *  Kotlin provides "data" classes. These are POJOs, where common
 *  functions like "equals/hashCode/toString/copy" are automatically
 *  provided with meaningful implementations.
 *
 * Created by arcuri82 on 12-Jul-17.
 */
data class NewsDto(

        /*
            Internally, the id is going to be a long value.
            But maybe in the future we could change it.
            So, an option is to just use a string, because
            anyway those ids are generated by the server, and
            not the client
         */
        @ApiModelProperty("The id of the news")
        var id: String? = null,

        @ApiModelProperty("The id of the author that wrote/created this news")
        var authorId: String? = null,

        @ApiModelProperty("The text of the news")
        var text: String? = null,

        @ApiModelProperty("The country this news is related to")
        @Country
        var country: String? = null,


        @ApiModelProperty("When the news was first created/published")
        var creationTime: ZonedDateTime? = null
)