spring:
  application:
    name: user-collections-service
  datasource:
    url: "jdbc:postgresql://postgres-user-collections:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate

