spring:
  mvc:
    throwExceptionIfNoHandlerFound: true
  resources:
    add-mappings: false
  application:
    name: user-collections-service
  cloud:
    consul:
     host: discovery
     port: 8500

cardServiceAddress: "cards-service:8080"