spring:
  mvc:
    throwExceptionIfNoHandlerFound: true
  resources:
    add-mappings: false
  application:
    name: user-collections-service
  cloud:
    consul:
     host: discovery
     port: 8500
  datasource:
    url: "jdbc:postgresql://postgres-user-collections:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate

cardServiceAddress: "cards-service:8080"