spring:
  mvc:
    throwExceptionIfNoHandlerFound: true
  resources:
    add-mappings: false
  application:
    name: cards-service
  session:
    store-type: none
  cloud:
    consul:
      host: discovery
      port: 8500
